/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  SmartAccountErrors,
  SmartAccountErrorsInterface,
} from "../SmartAccountErrors";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "smartAccount",
        type: "address",
      },
    ],
    name: "AlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "BaseImplementationCannotBeZero",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotAnEntryPoint",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotEntryPointOrOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "targetTxGas",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasPrice",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    name: "CanNotEstimateGas",
    type: "error",
  },
  {
    inputs: [],
    name: "EntryPointCannotBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "ExecutionFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementationAddress",
        type: "address",
      },
    ],
    name: "InvalidImplementation",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "restoredSigner",
        type: "address",
      },
      {
        internalType: "address",
        name: "expectedSigner",
        type: "address",
      },
    ],
    name: "InvalidSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nonceProvided",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonceExpected",
        type: "uint256",
      },
    ],
    name: "InvalidUserOpNonceProvided",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "MixedAuthFail",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gasLeft",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasRequired",
        type: "uint256",
      },
    ],
    name: "NotEnoughGasLeft",
    type: "error",
  },
  {
    inputs: [],
    name: "OwnerCannotBeZero",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "dest",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TokenTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferToZeroAddressAttempt",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "destLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "valueLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "funcLength",
        type: "uint256",
      },
    ],
    name: "WrongBatchProvided",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "contractSignature",
        type: "bytes",
      },
    ],
    name: "WrongContractSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "uintS",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "contractSignatureLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "signatureLength",
        type: "uint256",
      },
    ],
    name: "WrongContractSignatureFormat",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601357603a908160198239f35b600080fdfe600080fdfea26469706673582212200b9b2e0d2d6b0717c8a36650eaa1a2d7416cba991d573677333f8e8ed161a0ff64736f6c63430008110033";

type SmartAccountErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SmartAccountErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SmartAccountErrors__factory extends ContractFactory {
  constructor(...args: SmartAccountErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<SmartAccountErrors> {
    return super.deploy(overrides || {}) as Promise<SmartAccountErrors>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SmartAccountErrors {
    return super.attach(address) as SmartAccountErrors;
  }
  override connect(signer: Signer): SmartAccountErrors__factory {
    return super.connect(signer) as SmartAccountErrors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SmartAccountErrorsInterface {
    return new utils.Interface(_abi) as SmartAccountErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SmartAccountErrors {
    return new Contract(address, _abi, signerOrProvider) as SmartAccountErrors;
  }
}
