name: Tests
on:
  pull_request:
    branches:
      - develop
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: ./banana-wallet-sdk
      run: |
        npm install

    - name: Build the package
      working-directory: ./banana-wallet-sdk
      run: npm run build

    - name: Run tests
      working-directory: ./banana-wallet-sdk
      run: |
        node --max-old-space-size=4096 npm run test