/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SmartAccountFactoryErrors,
  SmartAccountFactoryErrorsInterface,
} from "../SmartAccountFactoryErrors";

const _abi = [
  {
    inputs: [],
    name: "AlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "BaseImplementationCannotBeZero",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotAnEntryPoint",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotEntryPoint",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotEntryPointOrOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotEntryPointOrSelf",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CallerIsNotOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "targetTxGas",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasPrice",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    name: "CanNotEstimateGas",
    type: "error",
  },
  {
    inputs: [],
    name: "DelegateCallsOnly",
    type: "error",
  },
  {
    inputs: [],
    name: "EntryPointCannotBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "ExecutionFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementationAddress",
        type: "address",
      },
    ],
    name: "InvalidImplementation",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "MixedAuthFail",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "module",
        type: "address",
      },
    ],
    name: "ModuleAlreadyEnabled",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "expectedModule",
        type: "address",
      },
      {
        internalType: "address",
        name: "returnedModule",
        type: "address",
      },
      {
        internalType: "address",
        name: "prevModule",
        type: "address",
      },
    ],
    name: "ModuleAndPrevModuleMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "module",
        type: "address",
      },
    ],
    name: "ModuleCannotBeZeroOrSentinel",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "module",
        type: "address",
      },
    ],
    name: "ModuleNotEnabled",
    type: "error",
  },
  {
    inputs: [],
    name: "ModulesAlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "ModulesSetupExecutionFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gasLeft",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasRequired",
        type: "uint256",
      },
    ],
    name: "NotEnoughGasLeft",
    type: "error",
  },
  {
    inputs: [],
    name: "OwnerCanNotBeSelf",
    type: "error",
  },
  {
    inputs: [],
    name: "OwnerCannotBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "OwnerProvidedIsSame",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "ProxyDeploymentFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenGasPriceFactorCanNotBeZero",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "dest",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TokenTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferToZeroAddressAttempt",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "destLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "valueLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "funcLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "operationLength",
        type: "uint256",
      },
    ],
    name: "WrongBatchProvided",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "contractSignature",
        type: "bytes",
      },
    ],
    name: "WrongContractSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "uintS",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "contractSignatureLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "signatureLength",
        type: "uint256",
      },
    ],
    name: "WrongContractSignatureFormat",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "moduleAddressProvided",
        type: "address",
      },
    ],
    name: "WrongValidationModule",
    type: "error",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220d5fc186bec4a584054f32af4511d456dca92e304c3a9f5dc64cd7e7a42a5dd1e64736f6c63430008110033";

export class SmartAccountFactoryErrors__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SmartAccountFactoryErrors> {
    return super.deploy(overrides || {}) as Promise<SmartAccountFactoryErrors>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SmartAccountFactoryErrors {
    return super.attach(address) as SmartAccountFactoryErrors;
  }
  connect(signer: Signer): SmartAccountFactoryErrors__factory {
    return super.connect(signer) as SmartAccountFactoryErrors__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SmartAccountFactoryErrorsInterface {
    return new utils.Interface(_abi) as SmartAccountFactoryErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SmartAccountFactoryErrors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SmartAccountFactoryErrors;
  }
}
